feat: add option for nomic-project-v2
nomic-ai/nomic pull request #279
Opened 2024-03-26 18:15 UTC by wilsonjr

2024-03-26 18:34 UTC, AndriyMulyar requested changes

2024-03-26 18:34 UTC, AndriyMulyar commented on nomic/dataset.py
> +        if projection.rho < 0.0 or projection.rho > 1.0:
This kind of check should be in the atlas api

2024-03-28 13:26 UTC, zanussbaum approved these changes

2024-03-28 13:27 UTC, etaldot approved these changes

2024-03-28 14:31 UTC, AndriyMulyar approved these changes

2024-03-28 14:31 UTC, merged